In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
df_full = pd.read_csv('full_tfidf_df.csv')
df_full.drop(columns=['Unnamed: 0'], inplace=True)
df_full[['num_tokens','mention_count','url_count','hashtag_count']] = df_full[['num_tokens','mention_count','url_count','hashtag_count']].fillna(0)
df_full=df_full.astype('int')

In [3]:
df_full

,aa,aaaaaaaaand,aaahhhhh,aahahah,aaliyah,aap,aaron,aaronmacgruder,aaryn,ab,...,zoote,zrgrizz,zuko,zulema,zulu,zzzzzz,num_tokens,mention_count,url_count,hashtag_count
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,15,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,17,2,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,7,2,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,13,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20615,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20616,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,11,0,0,0
20617,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20618,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,20,0,0,0
20619,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,7,1,1,0

In [5]:
features = df_full.drop(columns = 'class')
labels = df_full['class']

### Learning Curve (for memory reasons, ran on another notebook)

from sklearn.model_selection import learning_curve
from sklearn.linear_model import LogisticRegression

CV = 10
train_sizes = np.arange(500, 18500,500).tolist()
train_sizes, train_scores, validation_scores = learning_curve(
estimator = LogisticRegression(max_iter = 100000),
X = features,
y = labels, train_sizes = train_sizes, cv = CV,
scoring = 'accuracy')

import matplotlib.pyplot as plt

train_scores_mean = train_scores.mean(axis = 1)
validation_scores_mean = validation_scores.mean(axis = 1)
train_error = 1- train_scores_mean 
validation_error = 1 - validation_scores_mean 

plt.style.use('seaborn')
plt.plot(train_sizes, train_error, label = 'Training error')
plt.plot(train_sizes, validation_error, label = 'Validation error')
plt.ylabel('Error', fontsize = 14)
plt.xlabel('Training set size', fontsize = 14)
plt.title('Learning curves for a logistic regression model', fontsize = 18, y = 1.03)
plt.legend()

According to the learning curve, the validation error appears to increase after a training set of ~14500 (70%). Therefore, the optimal training size we'll use is 70%.

### Base logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size = 0.3, random_state = 0)

CV = 10
clf = LogisticRegression(max_iter = 100000)

y_pred = clf.fit(X_train, y_train)